"""
Action node responsible for dispatching tool calls to the execution service over RabbitMQ
with Human-in-the-Loop (HITL) authorization for critical operations.
"""

import time
import uuid
from typing import Any, Final

from langchain_core.messages import AIMessage, ToolMessage
from logger import get_logger
from rabbitmq import RabbitMQClient
from services.confirmation_manager import ConfirmationManager
from services.connection_manager import WebSocketConnectionManager

from ..hitl import generate_confirmation_context
from ..models import (
    AgentState,
    ConfirmationRequestPayload,
    EventEnvelope,
    EventMetadata,
    EventType,
    ToolExecutionRequestPayload,
)
from ..scheduler_tools import handle_scheduler_tool_execution

logger = get_logger("reasoning_engine.agent.action")

# Metadata identifiers and RPC conventions
DEFAULT_SOURCE_ID: Final[str] = "reasoning-engine"
TOOL_REQUEST_ROUTING_KEY_PREFIX: Final[str] = "tool.request."
STATUS_SUCCESS: Final[str] = "SUCCESS"
DEFAULT_TOOL_SUCCESS_OUTPUT: Final[str] = "Action completed."
MS_PER_SECOND: Final[int] = 1000

# Built-in critical tools requiring confirmation if not explicitly overridden by discovery
KNOWN_CRITICAL_TOOLS: Final[set[str]] = {"matar_proceso", "enviar_correo_electronico"}
SCHEDULER_TOOLS: Final[set[str]] = {
    "programar_tarea",
    "listar_tareas_programadas",
    "cancelar_tarea_programada",
    "pausar_reanudar_tarea",
}


class ActionNode:
    """
    Dispatches tool execution requests generated by the agent model to the
    external execution service via RabbitMQ RPC and collects the resulting ToolMessages.
    Enforces Human-in-the-Loop (HITL) authorization before executing critical actions.
    """

    def __init__(
        self,
        mq_client: RabbitMQClient,
        dynamic_tools: list[dict[str, Any]] | None = None,
        confirmation_manager: ConfirmationManager | None = None,
        ws_manager: WebSocketConnectionManager | None = None,
        email_service: Any | None = None,
        task_scheduler: Any | None = None,
    ) -> None:
        """
        Initialize the action node with injected messaging client and HITL dependencies.

        Args:
            mq_client: RabbitMQ RPC messaging client.
            dynamic_tools: Dynamic tools registry containing schema and criticality flags.
            confirmation_manager: Manager tracking pending user confirmation futures.
            ws_manager: WebSocket connection manager for dispatching confirmation modals to the frontend.
            email_service: Optional EmailAssistantService for semantic classification and draft creation.
            task_scheduler: Optional TaskSchedulerService for native task scheduling operations.
        """
        self._mq_client = mq_client
        self._dynamic_tools = dynamic_tools if dynamic_tools is not None else []
        self._confirmation_manager = confirmation_manager
        self._ws_manager = ws_manager
        self._email_service = email_service
        self._task_scheduler = task_scheduler

    def _get_tool_definition(self, tool_name: str) -> dict[str, Any] | None:
        """Look up tool descriptor dictionary from dynamic discovery registry."""
        for tool in self._dynamic_tools:
            if isinstance(tool, dict):
                func_meta = tool.get("function", {})
                if func_meta.get("name") == tool_name:
                    return tool
        return None

    def is_tool_critical(self, tool_name: str) -> bool:
        """
        Determine whether a tool is marked as critical and requires user confirmation.

        Args:
            tool_name: The name of the tool to evaluate.

        Returns:
            True if the tool is critical; False otherwise.
        """
        tool_def = self._get_tool_definition(tool_name)
        if tool_def is not None:
            return bool(tool_def.get("critical", False))

        return tool_name in KNOWN_CRITICAL_TOOLS

    async def _request_user_confirmation(
        self, tool_name: str, tool_args: dict[str, Any]
    ) -> bool:
        """
        Request interactive confirmation from the user over WebSocket for critical actions.

        Args:
            tool_name: The tool requiring authorization.
            tool_args: The arguments provided to the tool.

        Returns:
            True if approved by the user, False if denied or cancelled.
        """
        if self._confirmation_manager is None or self._ws_manager is None:
            logger.warning(
                "ConfirmationManager or WebSocketConnectionManager not available for critical tool '%s'. Proceeding with default authorization.",
                tool_name,
            )
            return True

        confirmation_id = f"conf-{uuid.uuid4()}"
        tool_def = self._get_tool_definition(tool_name)
        context_data = generate_confirmation_context(
            tool_name, tool_args, tool_def=tool_def
        )

        logger.info(
            "Requesting HITL confirmation for critical tool '%s' (conf_id=%s)",
            tool_name,
            confirmation_id,
        )

        future = self._confirmation_manager.create_confirmation(confirmation_id)

        try:
            confirmation_payload = ConfirmationRequestPayload(
                type="confirmation_request",
                confirmation_id=confirmation_id,
                tool_name=tool_name,
                arguments=tool_args,
                title=context_data.get("title", f"Confirmación de Acción: {tool_name}"),
                message=context_data.get(
                    "message", f"¿Desea autorizar la ejecución de '{tool_name}'?"
                ),
                severity=context_data.get("severity", "CRITICAL"),
                target=context_data.get("target", tool_name),
                details=context_data.get("details", {}),
            )

            await self._ws_manager.broadcast(
                confirmation_payload.model_dump(by_alias=False)
            )

            confirmed = await future
            return confirmed
        finally:
            self._confirmation_manager.remove(confirmation_id)

    async def __call__(self, state: AgentState) -> dict[str, Any]:
        """
        Dispatch all tool calls from the latest AI message and gather execution responses.

        Args:
            state: Current agent state dictionary.

        Returns:
            Dictionary containing the list of executed ToolMessage responses.

        Raises:
            TypeError: If the last message in state is not an AIMessage.
        """
        messages = state.get("messages", [])
        if not messages:
            return {"messages": []}

        last_message = messages[-1]
        if not isinstance(last_message, AIMessage):
            raise TypeError(
                f"Expected last message in state to be an AIMessage, but received {type(last_message).__name__}"
            )

        tool_messages: list[ToolMessage] = []

        for tool_call in last_message.tool_calls:
            tool_name = tool_call["name"]
            tool_args = tool_call["args"]
            tool_call_id = tool_call.get("id") or str(uuid.uuid4())

            # Handle native Python task scheduler tools
            if tool_name in SCHEDULER_TOOLS:
                logger.info(
                    "Executing native scheduler tool '%s' with args %s",
                    tool_name,
                    tool_args,
                )
                if self._task_scheduler:
                    result_text = await handle_scheduler_tool_execution(
                        tool_name, tool_args, self._task_scheduler
                    )
                else:
                    result_text = "Error: El servicio de tareas programadas (TaskSchedulerService) no está activo."

                tool_messages.append(
                    ToolMessage(content=result_text, tool_call_id=tool_call_id)
                )
                continue

            # Check if this tool is critical and requires user confirmation
            if self.is_tool_critical(tool_name):
                logger.info(
                    "Tool '%s' is critical. Initiating HITL authorization check...",
                    tool_name,
                )
                confirmed = await self._request_user_confirmation(tool_name, tool_args)

                if not confirmed:
                    logger.info(
                        "HITL authorization denied by user for tool '%s'", tool_name
                    )
                    cancellation_text = (
                        f"Operación cancelada por el usuario. No se ha ejecutado la acción '{tool_name}' "
                        f"en el sistema operativo debido a que el usuario denegó la autorización."
                    )
                    tool_messages.append(
                        ToolMessage(
                            content=cancellation_text, tool_call_id=tool_call_id
                        )
                    )
                    continue

                logger.info(
                    "HITL authorization granted by user for tool '%s'. Proceeding with OS execution.",
                    tool_name,
                )

            request_payload = ToolExecutionRequestPayload(
                tool_name=tool_name, arguments=tool_args
            )
            envelope = EventEnvelope(
                metadata=EventMetadata(
                    event_id=str(uuid.uuid4()),
                    correlation_id=str(tool_call_id),
                    timestamp=int(time.time() * MS_PER_SECOND),
                    source=DEFAULT_SOURCE_ID,
                    event_type=EventType.EXECUTION_REQUEST,
                ),
                payload=request_payload.model_dump(by_alias=True),
            )

            routing_key = f"{TOOL_REQUEST_ROUTING_KEY_PREFIX}{tool_name}"
            logger.info(
                "Dispatching tool execution request for '%s' (tool_call_id=%s)",
                tool_name,
                tool_call_id,
            )

            raw_response = await self._mq_client.send_and_wait(routing_key, envelope)

            if raw_response is None or not isinstance(raw_response, dict):
                result_text = f"Error: No response received from execution service for tool '{tool_name}'."
            else:
                payload = raw_response.get("payload", {})
                status = payload.get("status", STATUS_SUCCESS)
                output = payload.get("output", DEFAULT_TOOL_SUCCESS_OUTPUT)
                result_text = output if status == STATUS_SUCCESS else f"Error: {output}"

                # Trigger unread emails dispatch & classification for central zone
                if (
                    tool_name == "consultar_correos_no_leidos"
                    and status == STATUS_SUCCESS
                    and self._email_service
                    and self._ws_manager
                ):
                    try:
                        raw_emails = self._email_service.parse_emails_from_tool_output(
                            output
                        )
                        emails_payload = []
                        for raw_email in raw_emails:
                            classified = await self._email_service.classify_email(
                                raw_email
                            )
                            email_dict = {
                                "id": raw_email.id,
                                "account": raw_email.account,
                                "account_address": raw_email.account_address,
                                "subject": raw_email.subject,
                                "from_name": raw_email.from_name,
                                "from_address": raw_email.from_address,
                                "reply_to_address": raw_email.reply_to_address
                                or raw_email.from_address,
                                "to_addresses": raw_email.to_addresses,
                                "cc_addresses": raw_email.cc_addresses,
                                "received_at": raw_email.received_at,
                                "body_snippet": raw_email.body_snippet
                                or (
                                    raw_email.body_text[:200]
                                    if raw_email.body_text
                                    else ""
                                ),
                                "body_text": raw_email.body_text
                                or raw_email.body_snippet
                                or "",
                                "has_attachments": raw_email.has_attachments,
                                "attachment_names": raw_email.attachment_names,
                                "category": classified.category.value,
                                "urgency_score": classified.urgency_score,
                                "requires_reply": classified.requires_reply,
                                "suggested_action": classified.suggested_action,
                            }
                            emails_payload.append(email_dict)

                        if emails_payload:
                            await self._ws_manager.broadcast(
                                {
                                    "type": "unread_emails_list",
                                    "total": len(emails_payload),
                                    "emails": emails_payload,
                                }
                            )
                    except Exception as email_err:
                        logger.warning(
                            "Error processing email classification or drafts in ActionNode: %s",
                            email_err,
                        )

            tool_messages.append(
                ToolMessage(content=result_text, tool_call_id=tool_call_id)
            )

        return {"messages": tool_messages}


__all__ = [
    "DEFAULT_SOURCE_ID",
    "DEFAULT_TOOL_SUCCESS_OUTPUT",
    "KNOWN_CRITICAL_TOOLS",
    "MS_PER_SECOND",
    "STATUS_SUCCESS",
    "TOOL_REQUEST_ROUTING_KEY_PREFIX",
    "ActionNode",
]
