"""
Action node responsible for dispatching tool calls to the execution service over RabbitMQ.
"""
import time
from typing import Any, Dict, List
import uuid
from langchain_core.messages import AIMessage, ToolMessage

from ..models import (
    AgentState,
    EventEnvelope,
    EventMetadata,
    EventType,
    ToolExecutionRequestPayload,
)
from rabbitmq import RabbitMQClient


class ActionNode:
    """
    Dispatches tool execution requests generated by the agent model to the
    external execution service via RabbitMQ RPC and gathers the results into ToolMessages.
    """

    def __init__(self, mq_client: RabbitMQClient) -> None:
        """
        Initializes the action node with injected messaging dependencies.

        Args:
            mq_client: RabbitMQ RPC messaging client.
        """
        self._mq_client = mq_client

    async def __call__(self, state: AgentState) -> Dict[str, Any]:
        """
        Dispatches all tool calls from the last AI message and collects responses.

        Args:
            state: Current agent state dictionary.

        Returns:
            Dictionary containing the sequence of executed ToolMessage responses.
        """
        last_message = state["messages"][-1]
        assert isinstance(last_message, AIMessage), "Expected last message to be an AIMessage"

        tool_messages: List[ToolMessage] = []

        for tool_call in last_message.tool_calls:
            tool_name = tool_call["name"]
            tool_args = tool_call["args"]
            tool_call_id = tool_call.get("id") or str(uuid.uuid4())

            request_payload = ToolExecutionRequestPayload(
                toolName=tool_name, arguments=tool_args
            )
            envelope = EventEnvelope(
                metadata=EventMetadata(
                    eventId=str(uuid.uuid4()),
                    correlationId=str(tool_call_id),
                    timestamp=int(time.time() * 1000),
                    source="reasoning-engine",
                    eventType=EventType.EXECUTION_REQUEST,
                ),
                payload=request_payload.model_dump(by_alias=True),
            )

            routing_key = f"tool.request.{tool_name}"
            print(f" 🚀 [RabbitMQ] Dispatching execution request for: {tool_name}")

            # Await execution response from execution service without arbitrary timeout
            raw_response = await self._mq_client.send_and_wait(routing_key, envelope)

            payload = raw_response.get("payload", {})
            status = payload.get("status", "SUCCESS")
            output = payload.get("output", "Action completed.")

            result_text = output if status == "SUCCESS" else f"Error: {output}"
            tool_messages.append(
                ToolMessage(content=result_text, tool_call_id=tool_call_id)
            )

        return {"messages": tool_messages}
