python_version = "3.11"
python_platform = "windows"
python_interpreter_path = "reasoning-engine/.venv/Scripts/python.exe"
search_path = ["reasoning-engine"]
site_package_path = ["reasoning-engine/.venv/Lib/site-packages"]
